[package]
name = "inference_server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bench"
path = "src/bench.rs"

[dependencies]
rayon = "1.10.0"
threadpool = "1.8.1"
rand = "0.8.5"
libc = "0.2.155"

[build-dependencies]
cc = "1.0.98"
